<?php
declare(strict_types=1);
require __DIR__.'/../auth/bootstrap.php';require_once __DIR__.'/donations-lib.php';
header('Cache-Control: no-store');header("Content-Security-Policy: default-src 'none'; img-src 'self'; script-src 'self'; style-src 'self' 'unsafe-inline'; form-action 'self'; base-uri 'none'; frame-ancestors 'none'");
try{$db=shopStoreDatabase();$actor=npManagerId();}catch(Throwable $e){http_response_code(403);echo '<p>Увійдіть із підтвердженим email менеджера.</p><a href="/auth/">Вхід</a>';exit;}
$error='';$notice=(string)($_SESSION['donation_notice']??'');unset($_SESSION['donation_notice']);
if(($_SERVER['REQUEST_METHOD']??'GET')==='POST')try{
 shopCsrf($_POST);shopLimit($db,'donation-manager',20,60);$action=(string)($_POST['action']??'');
 if($action==='batch'){$image=shopDonationUpload($_FILES['screenshot']??[]);$batch=shopDonationBatch($db,$actor,$_POST,$image);$_SESSION['donation_notice']='Переказ № '.$batch.' збережено. Один скрін прикріплений до всіх обраних замовлень.';}
 elseif($action==='sent'){if(($_POST['sent_confirmed']??'')!=='yes')throw new RuntimeException('Підтвердьте фактичну ручну відправку.');shopDonationMarkSent($db,(int)($_POST['order_id']??0),$actor);$_SESSION['donation_notice']='Ручну відправку скріна позначено.';}
 else throw new RuntimeException('Невідома дія.');header('Location: /shop/donations.php',true,303);exit;
}catch(Throwable $e){$error=$e instanceof PDOException?'Не вдалося зберегти переказ. Оновіть список перед повтором.':$e->getMessage();}
// Accrue confirmed payments; this read does not send messages or cancel orders.
$missing=$db->query("SELECT o.id FROM rubizh_customer_orders o LEFT JOIN rubizh_order_donations d ON d.order_id=o.id WHERE o.payment_status='paid' AND o.status NOT IN ('cancelled','returned') AND d.order_id IS NULL ORDER BY o.id DESC LIMIT 100")->fetchAll(PDO::FETCH_COLUMN);foreach($missing as $id)shopRecordPaid($db,(int)$id);
$rows=shopDonationRows($db);$pending=array_filter($rows,fn($r)=>$r['batch_id']===null);$sum=(int)array_sum(array_column($pending,'amount'));
?><!doctype html><html lang="uk"><head><script src="/assets/theme.js?v=3"></script><link rel="stylesheet" href="/assets/theme.css?v=2"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>РУБІЖ · внески на ЗСУ</title><link rel="stylesheet" href="/shop/np-manager.css"><script defer src="/shop/donations.js"></script><link rel="stylesheet" href="/assets/theme.css?v=2"></head><body><header><a href="/">РУБІЖ</a><a href="/shop/np-manager.php">Замовлення</a><a href="/shop/settings.php">Налаштування</a></header><main>
<h1>Внески на ЗСУ · 47 ОМБр «Магура»</h1><p>3% від оплаченої вартості товарів, округлення до гривні для кожного замовлення. Скрін потрібно надіслати протягом 3 робочих днів після оплати. Перші відправки — вручну.</p>
<?php if($error):?><p class="error" role="alert"><?=esc($error)?></p><?php endif;?><?php if($notice):?><p class="notice" role="status"><?=esc($notice)?></p><?php endif;?>
<section class="card"><h2>Чекають скріна · <?=count($rows)?></h2><p>До нового переказу: <strong><?=$sum?> ₴</strong>. Обрано: <strong id="selected-donation-sum"><?=$sum?> ₴</strong>.</p>
<form method="post" enctype="multipart/form-data" id="donation-batch"><input type="hidden" name="csrf" value="<?=esc($_SESSION['csrf'])?>"><input type="hidden" name="action" value="batch"><input type="hidden" name="operation_key" value="<?=bin2hex(random_bytes(16))?>">
<?php foreach($pending as $r):?><label class="check <?=($r['due_at']<gmdate('Y-m-d H:i:s'))?'error':''?>"><input type="checkbox" name="orders[]" value="<?=(int)$r['order_id']?>" data-amount="<?=(int)$r['amount']?>" checked><span><?=esc($r['order_number'])?> · <?=(int)$r['amount']?> ₴ · до <?=esc(customerDate($r['due_at']))?><?=($r['due_at']<gmdate('Y-m-d H:i:s'))?' · ПРОСТРОЧЕНО':''?></span></label><?php endforeach;?>
<?php if($pending):?><div class="two"><label>Сума фактичного переказу, ₴<input id="donation-transfer-amount" type="number" name="amount" min="0" step="1" value="<?=$sum?>" required></label><label>Дата і час переказу (Київ)<input type="datetime-local" name="transferred_at" value="<?=(new DateTimeImmutable('now',new DateTimeZone('Europe/Kyiv')))->format('Y-m-d\TH:i')?>" required></label></div><label>Номер або реквізит переказу<input name="reference" maxlength="240" minlength="4" required></label><label>Скрін переказу · PNG, JPG або WebP до 8 МБ<input type="file" name="screenshot" accept="image/png,image/jpeg,image/webp" required></label><label class="check"><input type="checkbox" name="transfer_confirmed" value="yes" required> Кошти фактично переказані на 47 ОМБр «Магура»; сума і скрін відповідають обраним замовленням</label><button>Прикріпити один скрін до обраних замовлень</button><?php else:?><p>Оплачених замовлень для нового переказу немає.</p><?php endif;?></form></section>
<section class="card"><h2>Переказано · чекають ручної відправки</h2><p>Відкрийте чат, прикріпіть завантажений скрін і текст. Кнопка чату не надсилає повідомлення та не позначає доставку.</p>
<?php foreach($rows as $r):if(!$r['batch_id'])continue;$c=json_decode($r['contact_json']??'{}',true)?:[];$chat=shopDonationChat($c,(int)$r['amount']);?><article class="card <?=($r['due_at']<gmdate('Y-m-d H:i:s'))?'error':''?>"><h3><a href="/shop/np-manager.php?order=<?=(int)$r['order_id']?>"><?=esc($r['order_number'])?></a> · <?=(int)$r['amount']?> ₴<?=($r['due_at']<gmdate('Y-m-d H:i:s'))?' · ПРОСТРОЧЕНО':''?></h3><p>Переказ № <?=(int)$r['batch_id']?> · <?=esc($r['reference'])?> · <?=esc($chat['phone'])?> · <?=esc(ucfirst($chat['channel']))?></p><a class="button secondary" href="/shop/donation-proof.php?order=<?=(int)$r['order_id']?>&download=1">Завантажити скрін</a><?php if($chat['url']):?> <a class="button secondary" href="<?=esc($chat['url'])?>" target="_blank" rel="noopener">Відкрити <?=esc(ucfirst($chat['channel']))?></a><?php endif;?><label>Текст покупцю<textarea rows="3" readonly><?=esc($chat['text'])?></textarea></label><form method="post"><input type="hidden" name="csrf" value="<?=esc($_SESSION['csrf'])?>"><input type="hidden" name="order_id" value="<?=(int)$r['order_id']?>"><label class="check"><input type="checkbox" name="sent_confirmed" value="yes" required> Скрін і текст фактично надіслані покупцю</label><button name="action" value="sent">Позначити надісланим</button></form></article><?php endforeach;?></section>
<details class="card"><summary>Історія переказів та виключені після переказу замовлення</summary><?php foreach($db->query("SELECT b.id,b.amount,b.transferred_at,b.reference,COUNT(d.order_id) AS orders_count,SUM(CASE WHEN o.payment_status<>'paid' OR o.status IN ('cancelled','returned') THEN d.amount ELSE 0 END) AS excluded_amount FROM rubizh_donation_batches b JOIN rubizh_order_donations d ON d.batch_id=b.id JOIN rubizh_customer_orders o ON o.id=d.order_id GROUP BY b.id ORDER BY b.id DESC LIMIT 30")->fetchAll(PDO::FETCH_ASSOC) as $b):?><p>№ <?=(int)$b['id']?> · <?=(int)$b['amount']?> ₴ · <?=esc(customerDate($b['transferred_at']))?> · <?=esc($b['reference'])?> · замовлень: <?=(int)$b['orders_count']?><?php if((int)$b['excluded_amount']):?> · <strong class="error">Виключено після фактичного переказу: <?=(int)$b['excluded_amount']?> ₴. Перевірте повернення; здійснений переказ залишається в історії.</strong><?php endif;?></p><?php endforeach;?></details></main></body></html>
