<?php if(!defined('RUBIZH_AUTH')){http_response_code(404);exit;}$stage=$receipt['stage'];$ready=!empty($receipt['payment_ready']);$tone=['paid'=>'success','pending'=>'waiting','cancelled'=>'danger'][$stage];$note=['paid'=>'Дякуємо за ваше замовлення. Ми вже готуємо його до відправлення та повідомимо, коли посилка буде в дорозі.','pending'=>$ready?'Наявність підтверджено менеджером. Можна оплатити замовлення.':'Ми отримали замовлення. Менеджер перевірить наявність і комплектацію. Оплата стане доступною після підтвердження.','cancelled'=>'Це замовлення було скасовано. Якщо у вас виникли запитання — зверніться до нашої підтримки.'][$stage];?>
<article class="receipt-card" data-server-receipt data-order-number="<?=esc($receipt['number'])?>" data-order-status="<?=esc($receipt['status'].'|'.$receipt['payment_status'])?>" style="background:var(--<?=$tone?>-bg)"><div class="receipt-icon" aria-hidden="true"><?=['paid'=>'✓','pending'=>'◷','cancelled'=>'×'][$stage]?></div><span class="status-chip tone-<?=$tone?>"><?=['paid'=>'Оплачено','pending'=>$ready?'Очікує оплати':'Очікує підтвердження','cancelled'=>'Скасовано'][$stage]?></span><h1><?=esc($stage==='cancelled'?'Замовлення скасовано':$receipt['title'])?></h1><p class="receipt-intro"><?=esc($note)?></p><div class="receipt-summary"><div class="receipt-summary-row"><div><small>Номер замовлення</small><strong><?=esc($receipt['number'])?></strong></div><button type="button" class="copy-button" data-copy="<?=esc($receipt['number'])?>">Копіювати</button></div><div class="receipt-summary-row"><small><?=$stage==='pending'&&$ready?'Сума до оплати':'Сума замовлення'?></small><strong class="receipt-total"><?=esc(customerMoney($receipt['total']))?></strong></div></div>
<?php if($notice):?><p role="status"><?=esc($notice)?></p><?php endif;?><?php if($error):?><p role="alert"><?=esc($error)?></p><?php endif;?>
<?php if($stage==='pending'):?>
<?php if($receipt['payment_status']==='failed'):?><p>Оплата не пройшла — спробуйте ще раз.</p><?php endif;?>
<?php if($ready&&$receipt['payment_method']==='card'&&monoConfigured()):?><form method="post"><input type="hidden" name="csrf" value="<?=esc($_SESSION['csrf'])?>"><input type="hidden" name="order" value="<?=$id?>"><button class="receipt-main" name="action" value="retry">Сплатити замовлення →</button></form>
<?php elseif($ready&&$receipt['payment_method']==='invoice'):?><details class="receipt-requisites"><summary class="receipt-main">Сплатити замовлення →</summary><h2>Реквізити для оплати</h2><?php foreach(['Отримувач'=>$receipt['seller']['name'],'IBAN'=>$receipt['seller']['iban'],'ІПН'=>$receipt['seller']['tax_id'],'Сума'=>customerMoney($receipt['total']),'Призначення'=>'оплата замовлення '.$receipt['number']] as $label=>$value):?><p><?=esc($label)?>: <?=esc($value)?><button type="button" class="copy-button" data-copy="<?=esc($value)?>">Копіювати</button></p><?php endforeach;?><p>Банк: <?=esc($receipt['seller']['bank'])?>. Наявність підтверджено менеджером.</p></details><?php else:?><p>Очікуйте повідомлення менеджера. Оплата до підтвердження не потрібна.</p><?php endif;?>
<?php if($ready&&$receipt['payment_method']!=='cod'):?><p class="payment-deadline">Оплатіть до <?=esc($receipt['payment_due_label'])?> (Київ) — після цього резерв знімається. Нагадаємо через добу.</p><?php endif;?>
<?php if(shopNoOpenCardInvoice($db,$id)):?><form method="post"><input type="hidden" name="csrf" value="<?=esc($_SESSION['csrf'])?>"><input type="hidden" name="order" value="<?=$id?>"><button name="action" value="cancel" class="copy-button">Скасувати замовлення</button><?php if($receipt['payment_method']==='card'):?><button name="action" value="invoice" class="copy-button">Оплатити на рахунок ФОП</button><?php endif;?></form><?php else:?><p>Спосіб оплати та скасування доступні після остаточної звірки рахунку банку.</p><?php endif;?>
<?php elseif($stage==='paid'):?><a class="receipt-main" href="/auth/?tab=orders&amp;order=<?=$id?>">Переглянути замовлення →</a><?php else:?><a class="receipt-main" style="background:transparent;color:var(--text);border-color:var(--border)" href="/catalog">Повернутися до магазину →</a><?php endif;?>
<section class="receipt-next"><h2>◷ Що далі</h2><p><?php if($stage==='paid'):?>Ми збираємо ваше замовлення. Як тільки передамо його перевізнику, ви отримаєте повідомлення на email.<?php elseif($stage==='pending'&&!$ready):?>Перевіримо наявність і надішлемо повідомлення з переходом до оплати.<?php elseif($stage==='pending'):?>Після успішної оплати ми одразу підтвердимо замовлення та надішлемо вам лист із деталями.<?php elseif($receipt['payment_status']==='refunded'):?>Кошти повернено тим самим способом, яким ви оплатили.<?php elseif($receipt['was_paid']):?>Кошти повертаємо протягом 3 робочих днів тим самим способом, яким ви оплатили.<?php else:?>Оплата за це замовлення не була підтверджена. Ви можете оформити нове замовлення у зручний час.<?php endif;?></p></section>
<?php if($stage==='paid'):?><section class="receipt-donation"><h2>3% на <?=esc($receipt['brigade'])?></h2><p><?=esc($receipt['donation_text'])?></p><?php if(!empty($receipt['donation']['proof_url'])):?><p>Ваш внесок <?=(int)$receipt['donation_amount']?> ₴ — у цьому переказі разом із внесками інших покупців РУБІЖ.</p><a href="<?=esc($receipt['donation']['proof_url'])?>" target="_blank" rel="noopener">Переглянути скрін переказу →</a><?php endif;?></section><?php endif;?>
<details class="receipt-details"><summary>Деталі замовлення ▾</summary><?php foreach($receipt['items'] as $l):?><div class="receipt-line"><strong><?=esc($l['name'])?></strong><small><?=esc($l['variant']??'')?> · <?=esc($l['sku']??'')?></small><?=esc((string)$l['qty'])?> <?=($l['sale_unit']??'')==='m2'?'м²':'шт.'?> × <?=esc(customerMoney($l['price']))?></div><?php endforeach;?><p><?=esc($receipt['delivery'])?></p><p>Оплата: <?=esc(customerPayment($receipt['payment_status']))?>. Доставка — окремо за тарифом НП.</p><?php if($stage==='pending'):?><p>Після оплати <?=(int)$receipt['donation_amount']?> ₴ підуть на <?=esc($receipt['brigade'])?>.</p><?php endif;?></details></article>
