<?php
declare(strict_types=1);
require __DIR__.'/../auth/bootstrap.php';require_once __DIR__.'/settings-lib.php';
header("Content-Security-Policy: default-src 'none'; style-src 'self' 'unsafe-inline'; form-action 'self'; base-uri 'none'; frame-ancestors 'none'");header('Cache-Control: no-store');
try{$db=shopStoreDatabase();$actor=npManagerId();}catch(Throwable $e){http_response_code(403);echo '<p>Увійдіть із підтвердженим email менеджера.</p><a href="/auth/">Вхід</a>';exit;}
$error='';
if(($_SERVER['REQUEST_METHOD']??'GET')==='POST')try{
 if(!is_string($_POST['csrf']??null)||!hash_equals($_SESSION['csrf'],$_POST['csrf']))throw new RuntimeException('Оновіть сторінку.');
 if(isset($_SERVER['HTTP_ORIGIN'])&&!in_array($_SERVER['HTTP_ORIGIN'],['https://rubizh.shop','https://www.rubizh.shop'],true))throw new RuntimeException('Недозволений запит.');shopLimit($db,'site-settings',10,60);
 $raw=['seller'=>$_POST['seller']??[],'ga4_id'=>$_POST['ga4_id']??'','meta_pixel_id'=>$_POST['meta_pixel_id']??'','order_notification_email'=>$_POST['order_notification_email']??'','donation_enabled'=>isset($_POST['donation_enabled']),'donation_percent'=>$_POST['donation_percent']??3,'donation_report_url'=>$_POST['donation_report_url']??'','donation_schedule'=>$_POST['donation_schedule']??'','supplier_contacts'=>[]];
 foreach(is_array($_POST['supplier']??null)?$_POST['supplier']:[] as $code=>$row)if(is_array($row))$raw['supplier_contacts'][$code]=['channel'=>$row['channel']??'email','recipient'=>$row['recipient']??'','enabled'=>isset($row['enabled'])];
 shopSettingsSave($raw);npAudit($db,$actor,'site_settings_saved');$_SESSION['settings_notice']='Налаштування збережено. Оновіть вітрину, щоб перевірити зміни.';header('Location: /shop/settings.php',true,303);exit;
}catch(Throwable $e){$error=$e instanceof PDOException?'Не вдалося зберегти журнал. Перевірте результат перед повтором.':$e->getMessage();}
$notice=$_SESSION['settings_notice']??'';unset($_SESSION['settings_notice']);$seller=rubizhSeller();$contacts=cfg('supplier_contacts')??[];
?><!doctype html><html lang="uk"><head><script src="/assets/theme.js?v=3"></script><link rel="stylesheet" href="/assets/theme.css?v=2"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>РУБІЖ · налаштування магазину</title><link rel="stylesheet" href="/shop/np-manager.css"><link rel="stylesheet" href="/assets/theme.css?v=2"></head><body><header><a href="/">РУБІЖ</a><a href="/shop/np-manager.php">Замовлення і ТТН</a></header><main><h1>Налаштування магазину</h1><p>Реквізити, аналітика та контакти постачальників зберігаються на сервері. Ключі API редагуються в захищеній конфігурації хостингу.</p><?php if($notice):?><div class="notice"><?=esc($notice)?></div><?php endif;?><?php if($error):?><div class="error"><?=esc($error)?></div><?php endif;?>
<form method="post"><input type="hidden" name="csrf" value="<?=esc($_SESSION['csrf'])?>"><section class="card"><h2>Продавець</h2><div class="two"><?php foreach(['name'=>'Повне ім’я ФОП','tax_id'=>'РНОКПП','iban'=>'IBAN','bank'=>'Банк','mfo'=>'МФО','bank_tax_id'=>'ЄДРПОУ банку','address'=>'Адреса','email'=>'Email підтримки','phone'=>'Телефон у форматі +380…','phone_label'=>'Телефон для відображення'] as $k=>$label):?><label><?=esc($label)?><input name="seller[<?=esc($k)?>]" value="<?=esc($seller[$k])?>" maxlength="500"></label><?php endforeach;?></div><p class="muted">Застосовується до документів, футера, реквізитів оплати та листів. Перевірте дані перед прийманням платежів.</p></section>
<section class="card"><h2>Сповіщення й аналітика</h2><label>Email замовлень<input type="email" name="order_notification_email" required value="<?=esc((string)(cfg('order_notification_email')?:'zakaz@rubizh.shop'))?>"></label><div class="two"><label>GA4 ID<input name="ga4_id" placeholder="G-…" value="<?=esc((string)cfg('ga4_id'))?>"></label><label>Meta Pixel ID<input name="meta_pixel_id" placeholder="Числовий ID" value="<?=esc((string)cfg('meta_pixel_id'))?>"></label></div></section>
<section class="card"><h2>Підтримка війська</h2><p>3% на бригаду, вказану покупцем, після оплати; якщо не вказана — на 47 ОМБр «Магура». Один переказ для замовлень на одну бригаду; скрін покупцю у Viber або Telegram протягом 3 робочих днів.</p><a href="/shop/donations.php">Чекають скріна й історія переказів →</a><input type="hidden" name="donation_enabled" value="1"><input type="hidden" name="donation_percent" value="3"><input type="hidden" name="donation_schedule" value="Скрін переказу протягом 3 робочих днів після оплати"><label>HTTPS-посилання на публічні звіти (якщо є)<input type="url" name="donation_report_url" value="<?=esc((string)cfg('donation_report_url'))?>"></label></section>
<section class="card"><h2>Повідомлення постачальникам після ТТН</h2><p>Вкажіть підтверджений email або числовий Telegram chat_id. Telegram використовує серверний токен бота магазину. Для кожної посилки потрібні артикули постачальника: менеджер заповнює їх у замовленні до відправлення повідомлення.</p><?php foreach(npOrigins() as $code=>$origin):$c=$contacts[$code]??[];?><details><summary><?=esc($origin['name'])?></summary><label class="check"><input type="checkbox" name="supplier[<?=esc($code)?>][enabled]" <?=!empty($c['enabled'])?'checked':''?>> Автоматично сповіщати після створення ТТН</label><div class="two"><label>Канал<select name="supplier[<?=esc($code)?>][channel]"><option value="email">Email</option><option value="telegram" <?=($c['channel']??'')==='telegram'?'selected':''?>>Telegram</option></select></label><label>Email або chat_id<input name="supplier[<?=esc($code)?>][recipient]" value="<?=esc((string)($c['recipient']??''))?>"></label></div></details><?php endforeach;?></section><button>Зберегти налаштування</button></form>
<section class="card" style="margin-top:24px"><h2>Готовність сервісів</h2><p>Нова пошта: <?=npConfigured()?'ключ додано; потрібна перевірка відправника':'ключ не додано'?>. Випуск ТТН: <?=cfg('np_ttn_enabled')===true?'увімкнено':'вимкнено'?>.</p><p>monobank: <?=monoConfigured()?'налаштовано; перевірте тестову оплату':'вимкнено'?>. Telegram: <?=trim((string)cfg('tg_bot_token'))!==''&&trim((string)cfg('tg_chat_id'))!==''?'поля заповнено; перевірте доставку':'не всі поля заповнено'?>.</p><p>Фіди: <a href="/feeds/google.xml" target="_blank" rel="noopener">Google XML</a> · <a href="/feeds/meta.csv" target="_blank" rel="noopener">Meta CSV</a>. Нові дані публікує PIM; посилання залишаються незмінними.</p><p>Планувальник: notification-worker.php — щохвилини; mono-worker.php — раз на кілька хвилин; np-worker.php — кожні 15 хвилин; photo-worker.php — кожні 5 хвилин. notification-worker.php також обробляє нагадування та завершення строку оплати.</p></section></main></body></html>
