import {test} from 'node:test';
import assert from 'node:assert/strict';
import {spawnSync} from 'node:child_process';
import path from 'node:path';
const root=path.resolve(import.meta.dirname,'..'),runtime='/workspace/php-runtime/root/usr';
const pre=`require '${root}/shop/units.php';require '${root}/shop/pricing.php';function cfg($k){return $k==='shop_promo_codes'?['SAFE'=>5,'UNSAFE'=>30]:null;}function check($b,$m='check'){if(!$b)throw new Exception($m);}function denied($f,$reason){try{$f();throw new LogicException('accepted');}catch(ShopPricingException $e){check($e->reason===$reason,$e->reason);}}function policy($price=1590,$floor=1340,$kit=1370){return shopPricingPolicy(['pricing_policy_version'=>1,'price'=>$price,'minimum_sale_price'=>$floor,'discount_margin_floor_pct'=>15,'kit_price'=>$kit,'wholesale'=>[['price'=>1400],['price'=>1340]]]);}function line($p,$mode='retail',$qty=1){return ['sku'=>'sku','product_id'=>'p','price'=>shopMoneyValue($p['price_cents']),'qty'=>$qty,'price_mode'=>$mode,'kit_group'=>'custom','_pricing'=>$p,'catalog_version'=>'v'];}`;
function run(code){const r=spawnSync(runtime+'/bin/php8.4',['-n','-d','extension='+runtime+'/lib/php/20240924/mbstring.so','-r',pre+code],{encoding:'utf8',env:{...process.env,LD_LIBRARY_PATH:runtime+'/lib/x86_64-linux-gnu'},timeout:10000});assert.equal(r.status,0,r.stdout+'\n'+r.stderr);}
test('PIM retail, both wholesale levels and kit values are authoritative, percentage cannot change them',()=>run(`$p=policy();check(shopPricingUnit(line($p))===159000);$l=line($p,'wholesale');$l['_approved_wholesale_tier']=0;check(shopPricingUnit($l)===140000);$l['_approved_wholesale_tier']=1;check(shopPricingUnit($l)===134000);check(shopPricingUnit(line($p,'kit'))===137000);check(shopPricingPublic($p)['wholesale'][1]['discount']===15.7);`));
test('Expensive SKU uses passed 14710/13340/13700 without guessing the supplier payout',()=>run(`$p=shopPricingPolicy(['pricing_policy_version'=>1,'price'=>14710,'minimum_sale_price'=>13340,'discount_margin_floor_pct'=>15,'kit_price'=>13700,'wholesale'=>[['price'=>13340]]]);check(shopPricingUnit(line($p,'kit'))===1370000);check($p['minimum_cents']===1334000);`));
test('RRP/manual restrictions can raise every price and are never recalculated by shop',()=>run(`$p=shopPricingPolicy(['pricing_policy_version'=>1,'price'=>1700,'minimum_sale_price'=>1600,'discount_margin_floor_pct'=>15,'kit_price'=>1650]);check(shopPricingUnit(line($p,'kit'))===165000);denied(fn()=>shopPricingPolicy(['pricing_policy_version'=>1,'price'=>1700,'minimum_sale_price'=>1600,'discount_margin_floor_pct'=>15,'kit_price'=>1370]),'DISCOUNT_NOT_ALLOWED');`));
test('Missing floor, malformed floor and legacy pricing disable special discounts',()=>run(`foreach([null,'bad',2000] as $floor){$p=shopPricingPolicy(['pricing_policy_version'=>1,'price'=>1590,'minimum_sale_price'=>$floor,'discount_margin_floor_pct'=>15,'kit_price'=>100]);check($p['kit_cents']===null);denied(fn()=>shopPricingUnit(line($p,'kit')),'DISCOUNT_NOT_ALLOWED');}denied(fn()=>shopPricingUnit(['price'=>1590,'price_mode'=>'kit']),'DISCOUNT_NOT_ALLOWED');`));
test('Null kit price refuses special kit while retail remains available',()=>run(`$p=policy(1590,1340,null);check(shopPricingUnit(line($p))===159000);denied(fn()=>shopPricingUnit(line($p,'kit')),'INVALID_KIT');`));
test('Money rejects NaN, negative, subkopeck and boolean; fractional quantity is exact',()=>run(`foreach(['NaN',-1,1.001,true] as $v)denied(fn()=>shopMoney($v),'DISCOUNT_NOT_ALLOWED');check(shopMoney('100.01')===10001);check(shopLineMoney(10001,'1.25')===12501);`));
test('Wholesale cannot be self-approved or stack with promo; retail promo obeys exact floor',()=>run(`$p=policy();denied(fn()=>shopPricingUnit(line($p,'wholesale')),'DISCOUNT_NOT_ALLOWED');$raw=[line($p,'kit')];$calc=shopPriceLines($raw);denied(fn()=>shopCheckoutQuote($raw,'SAFE'),'DISCOUNT_NOT_ALLOWED');$raw=[line($p)];check(shopCheckoutQuote($raw,'SAFE')['total']===1510.5);denied(fn()=>shopCheckoutQuote($raw,'UNSAFE'),'DISCOUNT_NOT_ALLOWED');`));
test('Two separate plates are charged twice, packaged pair once; no duplicate size inference',()=>run(`$p=policy();$l=line($p,'kit',2);shopPricingKitComposition([$l]);check(shopCheckoutQuote([$l],'')['total']===2740);$p['kit_cents']=274000;$p['price_cents']=318000;$l=line($p,'kit',1);$other=line(policy(),'kit',1);$other['sku']='carrier';shopPricingKitComposition([$l,$other]);check(shopCheckoutQuote([$l,$other],'')['total']===4110);`));
test('Ready kit membership, exact SKU/color and complete quantity are checked',()=>run(`$l=line(policy(),'kit',2);$l['color']='Чорний';$l['kit_group']='b1';$defs=['b1'=>['items'=>[['product_id'=>'p','sku'=>'sku','color'=>'Чорний','qty'=>2]]]];shopPricingKitComposition([$l],$defs);$l['qty']=1;denied(fn()=>shopPricingKitComposition([$l],$defs),'INVALID_KIT');$l['qty']=2;$l['color']='Олива';denied(fn()=>shopPricingKitComposition([$l],$defs),'INVALID_KIT');`));
test('Public line quote never contains the margin floor, supplier constraints or wholesale grant',()=>run(`$l=line(policy(),'kit',2);$l['_approved_wholesale_tier']=1;$json=json_encode(shopCheckoutQuote([$l],''));check(!str_contains($json,'minimum')&&!str_contains($json,'_pricing')&&!str_contains($json,'approved'));check(shopCheckoutQuote([$l],'')['lines'][0]['price_mode']==='kit');`));
