import {test} from 'node:test';import assert from 'node:assert/strict';import {chromium} from 'playwright';import {startPreview} from '../dev/preview.mjs';import {products} from '../dev/fixtures.mjs';
async function browserTest(fn){const server=await startPreview(0),browser=await chromium.launch({executablePath:'/usr/bin/chromium',args:['--no-sandbox']});try{const page=await browser.newPage({viewport:{width:390,height:844}});page.setDefaultTimeout(8000);await fn(page,'http://127.0.0.1:'+server.address().port);}finally{await browser.close();await new Promise(r=>server.close(r));}}
function catalog(){return structuredClone(products).map(p=>({...p,variants:p.variants.map(v=>({...v,pricing_policy_version:1,kit_price:p.id==='demo-uniform'?2800.25:p.id==='demo-boots'?2700.25:v.price,wholesale:[{price:v.price-100,discount:Math.floor(100000/v.price)/10}]}))}));}
test('Selected SKU changes retail and actual wholesale amounts without exposing a private floor',()=>browserTest(async(page,base)=>{
 const p=catalog().find(p=>p.id==='demo-uniform');p.variants=p.variants.filter(v=>['L','M'].includes(v.size_display));p.variants[0].price=1590;p.variants[0].wholesale=[{price:1340,discount:15.7}];p.variants[1].price=1710.25;p.variants[1].wholesale=[{price:1500.25,discount:12.2}];
 await page.route('**/shop/catalog.php*',r=>{const a=new URL(r.request().url()).searchParams.get('action');if(a==='product')return r.fulfill({contentType:'application/json',body:JSON.stringify({ok:true,product:p})});if(a==='storefront')return r.fulfill({contentType:'application/json',body:JSON.stringify({ok:true,products:[p],kits:[]})});return r.continue();});
 await page.goto(base+'/product/demo-uniform');await page.getByRole('button',{name:p.variants[0].size_display,exact:true}).click();await page.locator('[data-wholesale-prices]').getByText(/1.340/).waitFor();assert.match(await page.locator('[data-wholesale-prices]').innerText(),/15.7%/);
 await page.getByRole('button',{name:p.variants[1].size_display,exact:true}).click();await page.locator('[data-wholesale-prices]').getByText(/1.500,25/).waitFor();assert.match(await page.locator('[data-wholesale-prices]').innerText(),/12.2%/);assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);
}));
test('Mobile kit total sums exact selected PIM kit prices instead of a quantity percentage',()=>browserTest(async(page,base)=>{
 const ps=catalog();await page.route('**/shop/catalog.php*',r=>{const a=new URL(r.request().url()).searchParams.get('action');if(a==='storefront')return r.fulfill({contentType:'application/json',body:JSON.stringify({ok:true,products:ps,kits:[]})});if(a==='ids')return r.fulfill({contentType:'application/json',body:JSON.stringify({ok:true,items:ps})});if(new URL(r.request().url()).searchParams.has('slot'))return r.fulfill({contentType:'application/json',body:JSON.stringify({ok:true,items:ps,total:ps.length,page:1,pages:1,facets:{leaves:[],sizes:[],camo:[]}})});return r.continue();});
 await page.goto(base+'/kit');
 for(const [slot,product,size] of [['Тіло','Тактичний костюм','L'],['Взуття','Берці','43']]){const tile=page.locator('.rz-kit-slot').filter({has:page.getByText(slot,{exact:true})});await tile.getByRole('button',{name:/Обрати спорядження|Додати/}).first().click();await page.locator('.rz-kit-modal-card').filter({hasText:product}).getByRole('button',{name:size,exact:true}).click();await page.locator('.rz-kit-modal').waitFor({state:'detached'});}
 await page.waitForFunction(()=>document.querySelector('.rz-kit-total')?.innerText.includes('5\u00a0500,5'));await page.locator('[data-kit-aside]').getByText(/599,5\s*₴/).waitFor();assert.doesNotMatch(await page.locator('[data-kit-aside]').innerText(),/−13%|Максимальн.*знижк|Більше позицій — більше вигоди/);
 await page.locator('[data-kit-bar]').getByRole('button',{name:'У кошик',exact:true}).click();await page.getByRole('heading',{name:'Оформлення замовлення'}).waitFor();assert.match(await page.locator('body').innerText(),/5\s*500,5\s*₴/);
}));
