import {test} from 'node:test';
import assert from 'node:assert/strict';
import {readFileSync,writeFileSync,mkdtempSync,mkdirSync,readdirSync,copyFileSync,rmSync} from 'node:fs';
import {spawnSync} from 'node:child_process';
import {tmpdir} from 'node:os';
import path from 'node:path';
const root=path.resolve(import.meta.dirname,'..'),runtime='/workspace/php-runtime/root/usr';
const phpArgs=['-n','-d','error_reporting=24575',...['pdo','mysqlnd','pdo_mysql','mbstring'].flatMap(e=>['-d',`${'extension='+runtime}/lib/php/20240924/${e}.so`]),'-d','pdo_mysql.default_socket='+process.env.RUBIZH_TEST_MYSQL_SOCKET];
function php(code){const r=spawnSync(runtime+'/bin/php8.4',[...phpArgs,'-r',code],{encoding:'utf8',timeout:120000,env:{...process.env,LD_LIBRARY_PATH:runtime+'/lib/x86_64-linux-gnu'}});assert.equal(r.status,0,r.stderr+r.stdout);return r.stdout;}
test('Semantic parsing resolves relations and complete phrases, while real primary-type conflicts remain for review',()=>{
 const cases=[
 ['Підсумок медичний з панеллю швидкого скидання','pouches_medical'],['Підсумок для скидання магазинів','pouches_dump'],['Підсумок під аптечку із вкладишем','pouches_medical'],
 ['Костюм (Кітель + Штани)','clothing_costumes'],['Акумуляторний LED ліхтарик','lighting_handheld'],['Акумулятор Westinghouse ICR18650','power_batteries'],
 ['Балістичний захист для поясу РПС','armor_soft'],['Плитоноска з балістичним пакетом','armor_carriers'],['Бронежилет + балістичний пакет','armor_vests'],
 ['Чохол для шолома','helmets_covers'],['Сумка для шолома','bags_tactical_bags'],['Кріплення для ПНБ','electronics_mounts'],['Підсумок для рації','pouches_radios'],
 ['Рюкзак тактичний 35 л','bags_backpacks'],['Рюкзак штурмовий 20 л','bags_assault'],['Баул транспортний 80 л','bags_duffel'],['Карта пам’яті','electronics_memory'],
 ['Шолом з Кавером Навушниками Ліхтариком','helmets_ballistic'],['Костюм маскувальний сітка мультикам','camouflage_suits'],['Маскувальна сітка','camouflage_nets'],
 ['Каремат-сидушка','field_seats'],['Футболка UBACS','clothing_combat_shirts'],['Тактична футболка','clothing_tshirts'],['Термостійкі рукавиці Чорні','clothing_gloves'],['Подушка M-WIN','field_other'],['Збройовий ремінь двоточка M-WIN','weapon_accessories_slings'],['Бойовий комплект (штани та Ubacs)','clothing_costumes'],['Підсумок рулонний під скидання KIBORG','pouches_dump'],['Підсумок під 6 магазінів АК','pouches_magazines'],['Килимок балістичний 2 класу','armor_soft'],['Плечові лямки для поясів РПС','load_bearing_shoulder'],['Флісова шарф-труба баф','clothing_balaclavas'],['Спрей від комах та кліщів','field_hygiene'],['Кишеньковий багатофункціональний інструмент 20 в 1','tools_tools']
 ];
 const result=JSON.parse(php(`require '${root}/shop/catalog-lib.php';require '${root}/shop/taxonomy-semantic-v2.php';$cases=json_decode('${JSON.stringify(cases)}',true);$out=[];foreach($cases as [$name,$expected]){$r=shopSemanticResolve(['name'=>$name]);$out[]=[$name,$r['category_id'],$expected,$r['status']];}echo json_encode($out);`));
 for(const [name,actual,expected,status] of result){assert.equal(actual,expected,name);assert.notEqual(status,'REAL_CONFLICT',name);}
 const other=JSON.parse(php(`require '${root}/shop/catalog-lib.php';require '${root}/shop/taxonomy-semantic-v2.php';echo json_encode([shopSemanticResolve(['name'=>'Бронежилет / Плитоноска / Комплект']),shopSemanticResolve(['name'=>'Швидке скидання']),shopSemanticResolve(['name'=>'Пам’ять'])]);`));
 assert.equal(other[0].status,'REAL_CONFLICT');assert.equal(other[1].status,'INSUFFICIENT_DATA');assert.equal(other[2].status,'INSUFFICIENT_DATA');
});
test('360 labelled real products across 18 roots retain their independently specified categories',()=>{
 const file=path.join(root,'tests/fixtures/classification-v2-golden.json');
 const result=JSON.parse(php(`require '${root}/shop/catalog-lib.php';require '${root}/shop/taxonomy-semantic-v2.php';$set=json_decode(file_get_contents('${file}'),true);$out=[];foreach($set['products'] as $p){$before=shopTaxonomyResolve($p);$after=shopSemanticResolve($p);$out[]=['id'=>$p['product_id'],'name'=>$p['name'],'expected'=>$p['expected_category_id'],'before'=>shopCanonicalCategoryId($before['category_id']),'after'=>$after['category_id'],'status'=>$after['status']];}echo json_encode($out);`));
 assert.equal(result.length,360);
 const wrong=result.filter(p=>p.expected!==p.after);assert.deepEqual(wrong,[]);
 const metrics={label_source:'Reviewed regression fixture; not a calibrated whole-catalogue accuracy estimate',products:result.length,correct_before:result.filter(x=>x.expected===x.before).length,correct_after:result.filter(x=>x.expected===x.after).length,fixed:result.filter(x=>x.expected!==x.before&&x.expected===x.after).length,regressions:result.filter(x=>x.expected===x.before&&x.expected!==x.after).length,false_conflicts:result.filter(x=>x.status==='REAL_CONFLICT').length};
 mkdirSync('/workspace/output/rubizh-reclassification-v2-20261008',{recursive:true});writeFileSync('/workspace/output/rubizh-reclassification-v2-20261008/golden-regression.json',JSON.stringify(metrics,null,2));
});
test('V2 dry-run is read-only; reviewed apply preserves data, manual locks and PIM authority across imports',{skip:!process.env.RUBIZH_TEST_MYSQL_SOCKET},()=>{
 const d=mkdtempSync(path.join(tmpdir(),'rubizh-v2-test-')),site=path.join(d,'www'),schema='fixture_v2_'+Math.random().toString(16).slice(2);mkdirSync(site);
 try{
  for(const folder of ['api','shop']){mkdirSync(path.join(site,folder));for(const f of readdirSync(path.join(root,folder)))if((f.endsWith('.php')||f==='canonical-taxonomy.json')&&!['config.php','mono-private.php','np-private.php'].includes(f))copyFileSync(path.join(root,folder,f),path.join(site,folder,f));}
  writeFileSync(path.join(site,'api/config.php'),`<?php return ['db_host'=>'localhost','db_name'=>'${schema}','db_user'=>'root','db_pass'=>'','media_dir'=>'${site}/media','cache_dir'=>'${site}/cache'];`);
  const code=String.raw`require '${site}/shop/reclassification-v2.php';$a=new PDO('mysql:unix_socket='.getenv('RUBIZH_TEST_MYSQL_SOCKET'),'root','');$a->exec('CREATE DATABASE ${schema} CHARACTER SET utf8mb4');function check($v,$m){if(!$v)throw new Exception($m);}try{$db=db();
   $items=[['medical','Підсумок медичний з панеллю швидкого скидання','Підсумки / Скидання магазинів'],['costume','Костюм (Кітель + Штани)','Одяг та форма / Штани'],['locked','Рюкзак тактичний 35 л','Рюкзаки, сумки та баули / Тактичні рюкзаки'],['pim','Акумуляторний LED ліхтарик','Автономне живлення / Акумулятори та батарейки'],['unknown','Річ без визначеного типу','Невідома категорія']];
   $payload=[];foreach($items as [$id,$name,$category]){$p=['id'=>$id,'slug'=>$id,'name'=>$name,'category'=>$category,'supplier_id'=>'S1','external_id'=>'native-'.$id,'description'=>'Original','variants'=>[['sku'=>$id.'-L','size_display'=>'L','color'=>'Мультикам','price'=>1000,'stock'=>5,'availability'=>'in']],'photos'=>['https://example.com/'.$id.'.jpg']];$payload[$id]=$p;check(save_product($db,$p)['status']!=='error','Seed');}
   shopTaxonomyApply($db,'${d}/old-backup');shopV2ManualLock($db,'locked','bags_assault','Confirmed by administrator');$lockedImport=$payload['locked'];$lockedImport['canonical_category_id']='bags_backpacks';check(save_product($db,$lockedImport)['status']!=='error','Pre-v2 locked import');check($db->query("SELECT category_id FROM rubizh_product_categories WHERE product_id='locked'")->fetchColumn()==='bags_assault','v1 import overwrote manual lock');
   $db->exec("UPDATE rubizh_product_categories SET category_id='power_batteries',reason='pim_canonical_id' WHERE product_id='pim'");
   $db->exec("INSERT INTO rubizh_catalog_supplier_articles VALUES('medical-L','medical','S1','NATIVE-MEDICAL',UTC_TIMESTAMP())");
   $before=shopTaxonomyAudit($db);$tables=$db->query('SHOW TABLES')->fetchAll(PDO::FETCH_COLUMN);$plan=shopV2Plan($db);check($before===shopTaxonomyAudit($db),'Dry-run changed rows');check($tables===$db->query('SHOW TABLES')->fetchAll(PDO::FETCH_COLUMN),'Dry-run issued DDL');
   check($plan['relations']['medical']['category_id']==='pouches_medical','Existing wrong relation reused');check($plan['relations']['costume']['category_id']==='clothing_costumes','Included pants won');check($plan['relations']['locked']['status']==='MANUAL_LOCK','Lock lost');check($plan['relations']['pim']['status']==='CATEGORY_ANOMALY'&&$plan['relations']['pim']['category_id']==='power_batteries','PIM authority changed');
   $sha=shopV2Export($plan,'${d}/report');$bad=false;try{shopV2Apply($db,'${d}/report/dry-run.json',str_repeat('0',64),'${d}/backup');}catch(RuntimeException $e){$bad=true;}check($bad,'Unreviewed checksum accepted');
   $result=shopV2Apply($db,'${d}/report/dry-run.json',$sha,'${d}/backup');check($result['protected_fingerprints_preserved'],'Integrity evidence');check($before['fingerprints']===shopTaxonomyAudit($db)['fingerprints'],'Price/SKU/photo/supplier data changed');
   check($db->query("SELECT category_id FROM rubizh_product_categories WHERE product_id='locked'")->fetchColumn()==='bags_assault','Locked assignment overwritten');shopV2Rollback($db,$result['backup']);check($before['fingerprints']===shopTaxonomyAudit($db)['fingerprints'],'Rollback changed protected rows');check($db->query("SELECT v FROM meta WHERE k='classifier_version'")->fetchColumn()===false,'Rollback left v2 active');$result=shopV2Apply($db,'${d}/report/dry-run.json',$sha,'${d}/backup');check($db->query("SELECT category_id FROM rubizh_product_categories WHERE product_id='medical'")->fetchColumn()==='pouches_medical','Apply after rollback differs');
   $p=$payload['locked'];$p['canonical_category_id']='bags_backpacks';$p['name']='Рюкзак оновлений';check(save_product($db,$p)['status']!=='error','Locked import blocked');check($db->query("SELECT category_id FROM rubizh_product_categories WHERE product_id='locked'")->fetchColumn()==='bags_assault','Import overwrote lock');
   $p=$payload['pim'];$p['canonical_category_id']='power_batteries';check(save_product($db,$p)['status']!=='error','PIM import failed');check($db->query("SELECT category_id FROM rubizh_product_categories WHERE product_id='pim'")->fetchColumn()==='power_batteries','Anomaly moved PIM category');$p['canonical_category_id']='lighting_handheld';check(save_product($db,$p)['status']!=='error','New PIM authority failed');check($db->query("SELECT category_id FROM rubizh_product_categories WHERE product_id='pim'")->fetchColumn()==='lighting_handheld','New PIM ID was ignored');$guarded=false;try{shopV2Rollback($db,$result['backup']);}catch(RuntimeException $e){$guarded=true;}check($guarded,'Rollback overwrote later import');
   $fresh=shopV2Plan($db);$newSha=shopV2Export($fresh,'${d}/fresh');$db->exec("UPDATE variants SET price=2000 WHERE sku='medical-L'");$stale=false;try{shopV2Apply($db,'${d}/fresh/dry-run.json',$newSha,'${d}/backup');}catch(RuntimeException $e){$stale=true;}check($stale,'Stale report applied');
   check((int)$db->query('SELECT COUNT(*) FROM rubizh_category_audit')->fetchColumn()>0,'No audit log');check((int)$db->query('SELECT COUNT(*) FROM rubizh_supplier_category_rules')->fetchColumn()===0,'Manual fix created a broad mass rule');
  }finally{$a->exec('DROP DATABASE ${schema}');}echo 'passed';`;
  assert.equal(php(code),'passed');
 }finally{rmSync(d,{recursive:true,force:true});}
});
