import {test} from 'node:test';
import assert from 'node:assert/strict';
import {mkdtempSync,mkdirSync,readdirSync,copyFileSync,writeFileSync,rmSync} from 'node:fs';
import {tmpdir} from 'node:os';
import path from 'node:path';
import {spawnSync} from 'node:child_process';
const root=path.resolve(import.meta.dirname,'..'),runtime='/workspace/php-runtime/root/usr';
test('Category migration is reversible, preserves full rows/media, filters old URLs and rejects unknown PIM IDs',{skip:!process.env.RUBIZH_TEST_MYSQL_SOCKET},()=>{
 const dir=mkdtempSync(path.join(tmpdir(),'rubizh-taxonomy-test-')),backup=mkdtempSync(path.join(tmpdir(),'rubizh-taxonomy-backup-')),schema='fixture_taxonomy_'+Math.random().toString(16).slice(2);
 try{
  for(const folder of ['api','shop']){mkdirSync(path.join(dir,folder));for(const f of readdirSync(path.join(root,folder)))if((f.endsWith('.php')||f==='canonical-taxonomy.json')&&!['config.php','mono-private.php','np-private.php'].includes(f))copyFileSync(path.join(root,folder,f),path.join(dir,folder,f));}
  mkdirSync(path.join(dir,'media'));writeFileSync(path.join(dir,'media','source.webp'),'original-image-byte-fixture');
  writeFileSync(path.join(dir,'api','config.php'),`<?php return ['db_host'=>'localhost','db_name'=>'${schema}','db_user'=>'root','db_pass'=>'','media_dir'=>'${dir}/media','media_url'=>'/media','cache_dir'=>'${dir}/cache'];`);
  const source=String.raw`require '${dir}/shop/taxonomy-migration.php';
  $db=new PDO('mysql:unix_socket='.getenv('RUBIZH_TEST_MYSQL_SOCKET').';charset=utf8mb4','root','',[PDO::ATTR_ERRMODE=>PDO::ERRMODE_EXCEPTION,PDO::ATTR_DEFAULT_FETCH_MODE=>PDO::FETCH_ASSOC]);$db->exec('CREATE DATABASE ${schema} CHARACTER SET utf8mb4');$db->exec('USE ${schema}');function check($ok,$msg){if(!$ok)throw new RuntimeException($msg);}try{migrate($db);
  $items=[['jacket','Куртка зимова',"Одяг та форма / Чоловічий одяг / Зимові та утеплені куртки",['Сезон'=>'Зима','supplier_id'=>'s1','external_id'=>'e1']],['female','Жіноча бойова сорочка UBACS',"Одяг та форма / Жіночий одяг / Убакси та бойові сорочки",['Стать'=>'Унісекс']],['net','Маскувальна сітка',"Маскування / Маскувальні сітки Militex / Мультикам",[]],['review','Невідомий предмет','Невідома гілка',[]]];
  $insert=$db->prepare('INSERT INTO products(id,slug,name,category_path,category_id,attributes,data,description,price_min,availability,visible,created_at,updated_at,synced_at) VALUES(?,?,?,?,?,?,?,?,?,?,1,UTC_TIMESTAMP(),UTC_TIMESTAMP(),UTC_TIMESTAMP())');
  foreach($items as [$id,$name,$category,$attrs]){$data=['id'=>$id,'slug'=>$id,'name'=>$name,'category'=>$category,'attributes'=>$attrs,'supplier_id'=>'s1','external_id'=>$id,'variants'=>[['sku'=>$id.'-L','size_display'=>'L','size_native'=>'L','price'=>1000,'kit_price'=>950,'stock'=>2,'availability'=>'in']],'photos'=>['https://example.com/'.$id.'.webp']];$insert->execute([$id,$id,$name,$category,sha1($category),json_encode($attrs),json_encode($data),'Source description',1000,'in']);$db->prepare("INSERT INTO variants(sku,product_id,size,color,price,kit_price,availability,data) VALUES(?,?,'L','Мультикам',1000,950,'in',?)")->execute([$id.'-L',$id,json_encode($data['variants'][0])]);$db->prepare("INSERT INTO photos(product_id,pos,src_url,src_hash,file,thumb,status,updated_at) VALUES(?,0,?,?,'source.webp','source.webp','ok',UTC_TIMESTAMP())")->execute([$id,'https://example.com/'.$id.'.webp',sha1($id)]);}
  $db->exec("INSERT INTO rubizh_catalog_supplier_articles VALUES('jacket-L','jacket','Supplier','NATIVE-123',UTC_TIMESTAMP())");recount_categories($db);$before=shopTaxonomyAudit($db);$tables=$db->query('SHOW TABLES')->fetchAll(PDO::FETCH_COLUMN);
  $dry=shopTaxonomyPlan($db);check($before===shopTaxonomyAudit($db),'Dry run changed data');check($tables===$db->query('SHOW TABLES')->fetchAll(PDO::FETCH_COLUMN),'Dry run created tables');check($dry['unassigned_products']===0&&count($dry['review'])===1,'Safety assignment');
  $r=shopTaxonomyApply($db,'${backup}');check($before['fingerprints']===$r['after']['fingerprints'],'Migration changed protected rows');check($r['after']['TOTAL_CATEGORY_RELATIONS']===4,'Missing relation');check(file_get_contents($r['backup'].'/media/source.webp')==='original-image-byte-fixture','Image backup');
  $cats=shopCategories($db);check(!in_array('__CATEGORY_REVIEW__',array_column($cats,'category_id'),true),'Internal category shown');check(!in_array('clothing_shorts',array_column($cats,'category_id'),true),'Empty category shown');check(max(array_map(fn($c)=>count(explode(' / ',$c['path'])),$cats))===2,'Excessive depth');
  $j=shopCatalogBuild($db,['category'=>'odiah-ta-forma/kurtky']);check($j['total']===1&&$j['items'][0]['canonical_category_id']==='clothing_jackets','Canonical lookup');check(shopCatalogBuild($db,['category'=>'clothing_jackets'])['total']===1,'ID lookup');check(shopCatalogBuild($db,['category'=>'__CATEGORY_REVIEW__'])['total']===0,'Internal ID exposed');
  $female=shopTaxonomyProduct($db,$db->query("SELECT * FROM products WHERE id='female'")->fetch());check(!isset($female['derived_attributes']['Стать']),'Precise gender overwritten');
  $redirect=shopTaxonomyRedirect($db,'odiah-ta-forma/cholovichyi-odiah/zymovi-ta-utepleni-kurtky',['sizes'=>'["L"]']);check(str_starts_with($redirect,'/catalog/odiah-ta-forma/kurtky?'),'Missing redirect');parse_str(parse_url($redirect,PHP_URL_QUERY),$params);check($params['sizes']==='["L"]'&&in_array('Сезон'."\1".'Зима',json_decode($params['attrs'],true),true),'Redirect lost filters');check(shopCatalogBuild($db,['category'=>'odiah-ta-forma/cholovichyi-odiah/zymovi-ta-utepleni-kurtky'])['total']===1,'Legacy API URL');
  check(shopCatalogBuild($db,['category'=>'maskuvannia/maskuvalni-sitky','attrs'=>json_encode(['Камуфляж'."\1".'Мультикам'])])['total']===1,'Derived filter missing');
  $q=$db->query("SELECT data FROM products WHERE id='jacket'")->fetchColumn();$payload=json_decode($q,true);$payload['canonical_category_id']='unknown-pim-id';$saved=save_product($db,$payload);check($saved['status']==='error','Unknown PIM ID accepted');check(shopTaxonomyAudit($db)['fingerprints']===$before['fingerprints'],'Unknown PIM ID changed product');check((int)$db->query('SELECT COUNT(*) FROM rubizh_category_sync_errors')->fetchColumn()===1,'Sync error not logged');
  $again=shopTaxonomyApply($db,'${backup}');check(shopTaxonomyAudit($db)['fingerprints']===$before['fingerprints'],'Repeated apply changed products');
  shopTaxonomyRollback($db,$again['backup']);check(shopTaxonomyActive($db),'Second rollback lost first migration');shopTaxonomyRollback($db,$r['backup']);check(!shopTaxonomyActive($db),'Rollback did not restore old structure');check(shopTaxonomyAudit($db)['fingerprints']===$before['fingerprints'],'Rollback lost data');
  shopTaxonomyApply($db,'${backup}');$payload['canonical_category_id']='clothing_pants';$saved=save_product($db,$payload);check($saved['status']!=='error','Known PIM ID failed');check($db->query("SELECT category_id FROM rubizh_product_categories WHERE product_id='jacket'")->fetchColumn()==='clothing_pants','PIM category not assigned');check((int)$db->query('SELECT COUNT(*) FROM variants')->fetchColumn()===4,'PIM duplicated variants');
  sync_categories($db,[['path'=>'Поставщик / Случайная категория']]);check(!$db->query("SELECT COUNT(*) FROM categories WHERE path='Поставщик / Случайная категория'")->fetchColumn(),'Supplier category created automatically');
  $current=shopTaxonomyAudit($db);$db->exec("UPDATE variants SET price=2000 WHERE sku='jacket-L'");$blocked=false;try{shopTaxonomyRollback($db,$r['backup']);}catch(RuntimeException $e){$blocked=true;}check($blocked,'Rollback overwrote later stock/price import');
  }finally{$db->exec('DROP DATABASE ${schema}');}echo 'passed';`;
  const args=['-n','-d','error_reporting=24575','-d','pdo_mysql.default_socket='+process.env.RUBIZH_TEST_MYSQL_SOCKET,...['pdo','mysqlnd','pdo_mysql','mbstring'].flatMap(e=>['-d',`extension=${runtime}/lib/php/20240924/${e}.so`]),'-r',source];
  const r=spawnSync(runtime+'/bin/php8.4',args,{encoding:'utf8',timeout:30000,env:{...process.env,LD_LIBRARY_PATH:runtime+'/lib/x86_64-linux-gnu'}});assert.equal(r.status,0,r.stdout+'\n'+r.stderr);assert.equal(r.stdout,'passed');
 }finally{rmSync(dir,{recursive:true,force:true});rmSync(backup,{recursive:true,force:true});}
});
