<?php if(!defined('RUBIZH_AUTH')){http_response_code(404);exit;}$badge=shopCustomerStatus($order);$receipt=$order['receipt'];$current=shopTimelineCurrent($order);$events=[];foreach($order['timeline'] as $e)$events[$e['event']][]=$e;?>
<section class="account-card order-detail" data-account-order="<?=esc($order['order_number'])?>" data-account-version="<?=esc(shopOrderUiVersion($order))?>" data-account-status="<?=esc($order['status'].'|'.$order['payment_status'])?>"><a class="back-link" href="/auth/?tab=orders&amp;view=<?=esc($orderView)?>">← Замовлення</a><h2>Деталі замовлення</h2><div class="card-heading"><strong>№ <?=esc($order['order_number'])?></strong><span class="status-chip tone-<?=esc($badge['tone'])?>"><?=esc($badge['label'])?></span></div><p><?=esc(customerDate($order['created_at']))?> <button class="copy-button" data-copy="<?=esc($order['order_number'])?>" type="button">Копіювати номер</button></p>
<ol class="order-timeline"><?php foreach(['created'=>'Замовлення створено','paid'=>'Оплачено','preparing'=>'Готуємо до відправлення','sent'=>'Передано Новій пошті','arrived'=>'Прибуло у відділення','received'=>'Отримано'] as $key=>$title):$event=$events[$key]??[];?><li class="<?=$event?'passed':'future'?> <?=$current===$key?'current':''?>" <?=$current===$key?'aria-current="step"':''?>><span class="timeline-dot"></span><div><strong><?=esc($title)?></strong><?php foreach($event as $entry):$details=json_decode($entry['detail_json'],true)?:[];?><small><?=!empty($details['observed'])?'Оновлено ':''?><?=esc((new DateTimeImmutable($entry['occurred_at'],new DateTimeZone('UTC')))->setTimezone(new DateTimeZone('Europe/Kyiv'))->format('d.m.Y H:i'))?><?php if($key==='paid'):?> · <?=esc(['card'=>'monobank','invoice'=>'Рахунок ФОП','cod'=>'При отриманні'][$details['method']??'']??'')?></small><?php elseif($key==='sent'):?></small><p><?=esc($details['tracking']??'')?></p><?php elseif($key==='arrived'):?></small><p><?=esc($details['address']??'')?><?php if(!empty($details['storage_until'])):?> · зберігання до <?=esc($details['storage_until'])?><?php endif;?></p><?php else:?></small><?php endif;?><?php endforeach;?></div></li><?php endforeach;?><?php foreach(['cancelled'=>'Скасовано','returned'=>'Повернено'] as $key=>$title):if(isset($events[$key])):?><li class="passed <?=$current===$key?'current':''?>" <?=$current===$key?'aria-current="step"':''?>><span class="timeline-dot"></span><div><strong><?=esc($title)?></strong><small><?=esc(customerDate($events[$key][0]['occurred_at']))?></small></div></li><?php endif;endforeach;?></ol>
<details class="order-products"><summary>▧ Товари у замовленні · <?=count($order['lines'])?><span class="order-thumbs"><?php foreach(array_slice($order['lines'],0,3) as $i=>$preview):$previewPhotos=$accountPhotos[$preview['product_id']??'']??[];$previewSrc=$previewPhotos[0]['thumb']??$previewPhotos[0]['url']??'';?><span class="order-thumb <?=$i===2?'third-thumb':''?>"><?php if($previewSrc):?><img src="<?=esc($previewSrc)?>" alt="<?=esc($preview['name'])?>" loading="lazy"><?php else:?>▧<?php endif;?></span><?php endforeach;?><?php if(count($order['lines'])>3):?><span class="order-thumb desktop-count">+<?=count($order['lines'])-3?></span><?php endif;?><?php if(count($order['lines'])>2):?><span class="order-thumb mobile-count">+<?=count($order['lines'])-2?></span><?php endif;?></span></summary><?php foreach($order['lines'] as $l):$photos=$accountPhotos[$l['product_id']??'']??[];$src=$photos[0]['thumb']??$photos[0]['url']??'';?><div class="order-product"><?php if($src):?><img src="<?=esc($src)?>" alt="" width="64" height="72" loading="lazy"><?php endif;?><div><a href="/product/<?=rawurlencode($l['slug']??$l['product_id']??'')?>"><?=esc($l['name'])?></a><small><?=esc($l['variant']??trim(($l['size']??'').' · '.($l['color']??''),' ·'))?></small><small><?=esc((string)$l['qty'])?> <?=($l['sale_unit']??'')==='m2'?'м²':'шт.'?> × <?=esc(customerMoney($l['price']))?></small></div></div><?php endforeach;?></details>
<div class="order-info"><span aria-hidden="true">▱</span><div><strong>Доставка Новою поштою</strong><p><?=esc($order['delivery_label']?:'Адреса доставки буде вказана під час підтвердження')?></p><?php foreach($order['shipments']??[] as $sh):?><p>ТТН <?=esc($sh['tracking_number'])?> <button type="button" class="copy-button" data-copy="<?=esc($sh['tracking_number'])?>">Копіювати</button> <a href="https://novaposhta.ua/tracking/?cargo_number=<?=rawurlencode($sh['tracking_number'])?>" target="_blank" rel="noopener">Відстежити →</a></p><?php endforeach;?></div></div>
<div class="order-info"><span aria-hidden="true">₴</span><div><span>Сума замовлення</span><strong class="order-large-sum"><?=esc(customerMoney($order['total']))?></strong></div></div>
<p>Оплата: <?=esc(customerPayment($order['payment_status']))?></p><?php if($receipt['stage']==='pending'):?><a class="button inline-button" href="<?=esc($receipt['payment_url'])?>"><?=!empty($receipt['payment_ready'])?'Сплатити замовлення →':'Очікує підтвердження →'?></a><a class="button inline-button secondary" href="<?=esc($receipt['payment_url'])?>">Скасувати замовлення →</a><?php endif;?>
<?php if(in_array($order['status'],['delivered','completed','cancelled'],true)):?><a class="button inline-button secondary" href="/#cart?repeat=<?=(int)$order['id']?>">Повторити замовлення →</a><?php endif;?>
<a class="button inline-button secondary" href="mailto:<?=esc(rubizhSeller()['email'])?>?subject=<?=rawurlencode('Замовлення '.$order['order_number'])?>">Звʼязатися з нами →</a>
<section class="donation-order"><h3>Внесок на ЗСУ</h3><p><?=esc($order['donation_text'])?></p><?php if(!empty($order['donation']['proof_url'])):?><a href="<?=esc($order['donation']['proof_url'])?>" target="_blank" rel="noopener">Переглянути скрін →</a><?php elseif(!empty($order['donation']['due_at'])):?><p>Скрін надішлемо до <?=esc(customerDate($order['donation']['due_at']))?>.</p><?php endif;?></section>
</section>
